### ISSUE TITLE
Allow user to customize which hook to attach the automatic check to

### ISSUE THREAD

**Issue by simoneb** [nearform/fastify-casbin-rest#3]
Currently, `preHandler` is used. 

A more sensible default would be `onRequest`, which is early enough to guarantee that no unnecessary operations are done on a request that's eventually going to be forbidden by authorization rules.

Clearly, if that becomes the default, any logic which needs to happen before authorization also needs to happen earlier in the request lifecycle. The examples and example application need to change to do authentication earlier (onRequest VS preValidation)

**Comment by kibertoad** [comment]
Can I pick this one up?
