### ISSUE TITLE
Support four-part checks

### ISSUE THREAD

**Issue by kibertoad** [nearform/fastify-casbin-rest#5]
For ACL-style checks it might be more convenient to separate `object-type` and `object-id` parts of the check (casbin seems to support that). Currently this can be worked around by concatenating both of them into single `object` entity, but it is not exactly elegant.

**Comment by simoneb** [comment]
Yes I'm aware of this limitation, I just didn't know a good way to model that in the plugin, because obj, sub, act are the 3 common entities, above those you go in the realm of the custom implementation.

**Comment by kibertoad** [comment]
@simoneb I would say that for all intents and purposes of this plugin the actual set of entities is not that important, so it could expose one config param for extracting whatever needs to be extracted and returning it as a single object, and then another config param that would expose handler for how that object will be fed to the casbin. If user would choose to implement extraction logic in more granular fashion, they could do so within their unified extractor implementation.

**Comment by simoneb** [comment]
I didn't think about splitting the two things, in my mind the entities you extract from the request are those which are provided automatically to the .enforce method. I had a feeling that anything beyond that would fall outside the scope of this plugin and instead into a custom usage of the base fastify-casbin plugin. But I'm open to suggestions which wouldn't deviate too much from the intent of this plugin. The more we customize this the more this becomes something else than a "rest" plugin, if you know what I mean.

**Comment by kibertoad** [comment]
Yeah, fair, and it's also `opinionated plugin`, so I guess encouraging user to apply particular pattern might be a feature here. My only concern here is that particularly for implementing REST ACL three-piece checks are generally insufficient, unless concatenation is applied - which I guess is fine, if done inside the extraction part.

**Comment by kibertoad** [comment]
What was your own use-case? RBAC style auth?

**Comment by simoneb** [comment]
In fairness, this extension to the base plugin was more of a thought experiment without a real use case

**Comment by kibertoad** [comment]
@simoneb Since concatenating entity type with entity id as single `obj` poses problems when defining rules (e. g. then you can't flexibly define role inheritance across specific entity types), would you be open to introducing optional param `dom` that is only used when not resolved to `undefined` and which is not extracted by default?
It is used in many of `node-casbin` examples, e. g. https://github.com/casbin/node-casbin/blob/master/examples/rbac_with_domain_pattern_model.conf

**Comment by simoneb** [comment]
I'm not against this, what would the API look like?

**Comment by kibertoad** [comment]
@simoneb Gave it a shot, please see linked PR; I think this is the most non-intrusive way possible, and I don't think that there should be customization beyond (rather common) 4-part policies with domain, since, as you've pointed out, this is an opinionated plugin that prescribes particular frame for doing things.
